---
title: "Interrupts"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Interrupts}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


## Overview

Interrupts in `webqueue` fall into three categories:

1. **Timeout** - set before the request starts processing.
2. **Replacement** - a later request replaces an earlier one.
3. **Custom** - your code calls 
   [`<job>$stop()`](https://cmmr.github.io/jobqueue/reference/job_class.html#method-stop-).


### Requests vs Jobs

A request (`req`) is an environment with the data sent from a web browser to 
the web server. A `job` is a 
[`jobqueue::job_class` R6 object](https://cmmr.github.io/jobqueue/reference/job_class.html) 
containing a single `req` along with the parameters for processing it.

Some useful elements of each are:

<table><tr><td>

* `req$ARGS`
* `req$COOKIES`
* `req$PATH_INFO`
* `req$REMOTE_ADDR`

</td><td>

* `job$result`
* `job$timeout`
* `job$on()`
* `job$stop()`

</td></tr></table>

Interrupts are always defined at the 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html) level.


## Setup

```r
library(webqueue)

# By default, returns "hello" immediately.
# Adding '?return=myvalue' will return "myvalue" instead.
# Adding '?sleep=2' will wait 2 seconds before returning.
handler <- function (req) {
  args <- req$ARGS # POST/GET parameters
  if (!is.null(args$sleep))  Sys.sleep(args$sleep)
  if (!is.null(args$return)) args$return else 'hello'
}

```

To interrupt a 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html) from within
`handler`, call `stop()` or `cli_abort()` as usual, or 
`return (webqueue::response())` to send a more informative message back.



## Timeout


### Basic

Let's start by limiting all 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html)s to 1 second.

```r
wq <- webqueue(handler, timeout = 1)

getURL('http://localhost:8080')
#> [1] "hello"

getURL('http://localhost:8080?return=hi')
#> [1] "hi"

getURL('http://localhost:8080?sleep=3')
#> [1] "timeout: total runtime exceeded 1 second\n"

wq$stop()
```


### Per State

Setting `timeout = 1` is shorthand for `timeout = c(total = 1)`, which starts 
the clock as soon as the 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html) is created. 
If these [`job`](https://cmmr.github.io/jobqueue/reference/job_class.html)s are 
likely to wait a long time before running, you might consider setting 
`timeout = c(running = 1)` which starts the clock when the 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html) actually 
begins running. Or, set `timeout = c(running = 1, queued = 60)` to also set a 
limit to how long a 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html) can spend 
waiting in the queue.

See the 
[`jobqueue::job_class`](https://cmmr.github.io/jobqueue/reference/job_class.html#method-job-on)
reference page for information on all standard `job` states.

```r
wq <- webqueue(handler, timeout = c(queued = 1))

# spend 3 seconds in 'running' state
getURL('http://localhost:8080?sleep=3')
#> [1] "hello"

wq$stop()
```


### Per Request

Perhaps some pages on your website need a different time limit.

```r
timeout <- function (job) {
  ifelse(job$req$PATH_INFO == '/compute', 5, 1)
}

wq <- webqueue(handler, timeout = timeout)

getURL('http://localhost:8080/compute?sleep=3')
#> [1] "hello"

getURL('http://localhost:8080?sleep=3')
#> [1] "timeout: total runtime exceeded 1 second\n"

wq$stop()
```



## Replacement

Use the `stop_id` field to only run the most recent request with a given hash.

For instance, if you have a session id (`id`) you can use that as the request hash.


```r
wq <- webqueue(
  handler = handler, 
  stop_id = function (job) { job$req$ARGS$id } )

# Fetch three URLs at the same time.
responses <- fetch(
  first  = 'http://localhost:8080?id=1&sleep=1&return=first',
  second = 'http://localhost:8080?id=1&sleep=1&return=second',
  third  = 'http://localhost:8080?id=1&sleep=1&return=third' ))

responses$first
#> [1] "superseded: duplicated stop_id\n"

responses$second
#> [1] "superseded: duplicated stop_id\n"

responses$third
#> [1] "third"

wq$stop()
```


### Cancel

You can also send a dummy request with the appropriate `stop_id` hash to cancel 
an actual request.




## Custom

Anywhere you provide a `function (job)`, you can examine 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html) and `req`, 
and call `job$stop()` as needed.

### IP Filter

To ignore requests from certain IP addresses:

```r
ip_check <- function (job) {
  ip <- job$req$REMOTE_ADDR
  if (!startsWith(ip, '192.168.'))
    job$stop(paste('Unauthorized IP Address:', ip))
}

wq <- webqueue(handler, hooks = list(created = ip_check))

fetch('http://localhost:8080')
#> [1] "interrupt: Unauthorized IP Address: 127.0.0.1\n"

wq$stop()
```

Note: in reality, you'd want to use `webqueue(onHeaders)` to do 
this particular task more efficiently.


### Limit Concurrency

Once the job is assigned to a `jobqueue`, you can access the list of all 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html)s that are 
currently queued or running.

Here, we'll refuse to add more than 2 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html)s to the 
[`jobqueue`](https://cmmr.github.io/jobqueue/reference/jobqueue_class.html) at 
once.

```r
qlimit <- function (job) {
  if (length(job$queue$jobs) > 2)
    job$stop('Too many concurrent jobs.')
}

wq <- webqueue(handler, hooks = list(queued = qlimit))

# Fetch three URLs at the same time.
dput(fetch(
  'http://localhost:8080?sleep=1',
  'http://localhost:8080?sleep=1',
  'http://localhost:8080?sleep=1' ))
#> c("hello", "hello", "interrupt: Too many concurrent jobs.\n")

wq$stop()
```

### Stop Other Jobs

Suppose an admin needs to stop all 
[`job`](https://cmmr.github.io/jobqueue/reference/job_class.html)s 
for a particular user.

```r
stop_user <- function (job) {

  stop_uid <- job$req$ARGS$stop
  if (!is.null(stop_uid)) {
  
    for (j in job$queue$jobs)
      if (j$req$ARGS$uid == stop_uid)
        j$stop('Stopped by admin.')
    
    job$output <- 'done'
  }
}

wq <- webqueue(handler, hooks = list(queued = stop_user))

# Fetch three URLs at the same time.
responses <- fetch(
  'http://localhost:8080?uid=1&sleep=10',
  'http://localhost:8080?uid=1&sleep=10',
  'http://localhost:8080?uid=2&stop=1' )

responses[[1]]
#> [1] "interrupt: Stopped by admin.\n"

responses[[2]]
#> [1] "interrupt: Stopped by admin.\n"

responses[[3]]
#> [1] "done"

wq$stop()
```




